############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "About"
url = "/about"
weight = 2

[[main]]
weight = 3
name = "Courses"
url = "/courses"

[[main]]
weight = 4
name = "Publications"
url = "/publications"

# footer menu
[[footer]]
name = "About"
url = "/about"
weight = 1

